# Make the application available at http://localhost:8080
# These are default settings, but we add them for clarity.
server:
  port: 8080
  contextPath: /

# Configure the Authorization Server and User Info Resource Server details
security:
  oauth2:
    client:
      accessTokenUri: http://localhost:9090/auth/oauth/token
      userAuthorizationUri: http://localhost:9090/auth/oauth/authorize
      clientId: myauthserver
      clientSecret: verysecretpassword
    resource:
      userInfoUri: http://localhost:9090/auth/user
      
